### PR TITLE
Add an initial language switch to the footer

### PR DESCRIPTION
**Pull request by tokideveloper**

### CODE REVIEW

**Comment by marmarek** [comment]
I think the current language should be in bold, but also there should be some text that it is about the language, for example add "Website language:" before (in the header we have an icon for this purpose)

**Comment by tokideveloper** [comment]
> I think the current language should be in bold,

It's already embraced in `strong` tags which seem to have the same effect as with `b` tags. But we could underline (`u`) it additionally for better visibility.

> but also there should be some text that it is about the language, for example add "Website language:" before (in the header we have an icon for this purpose)

IMHO, text can be very expressive but only if you know the language (also there is the problem whether it should be translated or not). A single icon should work better here. We could use the same icon as in the header.

@marmarek What do you think?

**Comment by marmarek** [comment]
Yes, an icon would be better indeed.
as for marking the current one, maybe that's because of the font we use? It isn't much different than surrounding text (footer links etc). Maybe try underline...

**Comment by tokideveloper** [comment]
@marmarek

> Yes, an icon would be better indeed.

See the attachments. Choose your icon size (16, 20 or 24 px). I prefer 24 due to its better readability.

> as for marking the current one, maybe that's because of the font we use? It isn't much different than surrounding text (footer links etc).

I don't know but if I had to guess I would say yes.

> Maybe try underline...

See the attachments, too.

16x16: screenshot_langswitch_16px
20x20: screenshot_langswitch_20px
24x24: screenshot_langswitch_24px

**Comment by marmarek** [comment]
I like the 24 one too. And yes, underline does the job :)

**Comment by marmarek** [comment]
@tokideveloper I updated the version on wwwtest.qubes-os.org, with this PR included.
And noticed one weird case: on the main site, if you click on "de", it will show you directory listing, not the actual site. That seems to be because there is no translation for the main page (perhaps I did something wrong when uploading/downloading it to transifex)? But with the switcher at the top, "de" is not listed as an option.

I did uncommented "de" in `_data/l10n/langs.yml`, but since the switcher at the top correctly detect if the page is translated or not, perhaps the same mechanism can be used in the switcher in the footer?

cc @maiska

**Comment by tokideveloper** [comment]
> I updated the version on wwwtest.qubes-os.org, with this PR included.

Nice! Thank you!

> And noticed one weird case: on the main site, if you click on "de", it will show you directory listing, not the actual site. That seems to be because there is no translation for the main page (perhaps I did something wrong when uploading/downloading it to transifex)? But with the switcher at the top, "de" is not listed as an option.
> 
> I did uncommented "de" in `_data/l10n/langs.yml`, but since the switcher at the top correctly detect if the page is translated or not, perhaps the same mechanism can be used in the switcher in the footer?

The most recent plan is that we want to download all files in all languages even if they are 0 percent translated. This simplifies things (like the switcher). @maiska Can you confirm this?
This means that you should download all files in all languages (except `en`) that are listed in `_data/l10n/langs.yml` and push them online.

**Pull request merged**
